### ISSUE TITLE
kwin slows down to crawl when playing full screen video in mpv

### ISSUE THREAD

**Issue by sashaaaaaaaaa** [tildearrow/kwin-lowlatency#89] opened 2020-06-25 14:49 UTC
Basically you get 18fps if you're playing a video full screen so if you wanna watch a video on another screen while doing something on the other it's impossible in full screen with the low latency version

**Comment by sashaaaaaaaaa** [comment] 2020-06-25 14:51
Oh I see this has already been mentioned here: https://github.com/tildearrow/kwin-lowlatency/issues/7#issuecomment-630726826

**Comment by tildearrow** [comment] 2020-06-25 16:49
Hmm... This appears to be caused by a usleep code that runs when full-screen unredirection is active (to prevent the compositor from taking 100% of the CPU).

Let me see if I can add a way to detect multi-monitors...

**Comment by tildearrow** [comment] 2020-06-25 17:14
Please try with latest commit from Plasma/5.19 branch (if you are on 5.18 tell me). I think I may have added a fix.

**Comment by sashaaaaaaaaa** [comment] 2020-06-25 20:26
Yeah that's much better it only dips about 10fps playing now with vsync on with the proprietary nvidia driver. 

and if you turn vsync off and turn on the forcecompositionpipeline from the nvidia driver instead, it goes up to 100fps fullscreened. like when you don't have that option turned on.

**Comment by Kodehawa** [comment] 2020-06-29 23:06
It fixes it for me. I mean it does slow down a bit still, but not to a crawl.

**Comment by tildearrow** [comment] 2021-11-24 05:52
Fixed in 5.22+ with the rewrite.

**Closed as completed by tildearrow** 2021-11-24 05:52 UTC
Labels: bug, done
