### ISSUE TITLE
Is this supposed to work on Nvidia?

### ISSUE THREAD

**Issue by Sporif** [tildearrow/kwin-lowlatency#2] opened 2019-04-04 11:46 UTC
It doesn't seem make a difference on Nvidia. Firefox still stutters while scrolling, so setting the `MaxFPS` option is still needed to make it smooth. I tried adding the ` modeset=1` parameter to `nvidia_drm`, but that didn't make a difference. Nor did the sync to vblank option in nvidia-settings.

I also tried using nouveau but that didn't even have vsync working and was stuttery, though I did see multiple lines of tearing.

If it matters I tried both the 5.15.3 and 5.15.4 versions.

**Comment by tildearrow** [comment] 2019-04-04 17:28
I don't own any NVIDIA cards anymore, so I can't assure it works there.

Do you have multiple cards (including integrated ones?) (do `ls /dev/dri/card*` to find out)? If so then you may need to tweak the value of `#define drmcard` in composite.cpp and then recompile.

(if you don't, I'll create a separate branch which relies upon waiting for SwapBuffers to finish instead, since MaxFramesAllowed is now in place)

**Comment by Sporif** [comment] 2019-04-04 17:32
I have only one card.

**Comment by tildearrow** [comment] 2019-04-05 18:45
Why does MaxFPS have an effect on stuttering? KWin-lowlatency ignores its value. Are you sure you are running/installing it correctly?

**Comment by Sporif** [comment] 2019-04-05 21:46
I just tried it again and MaxFPS didn't do anything.

**Comment by tildearrow** [comment] 2019-04-06 06:53
I'm so sorry but I can't really do much since I don't have any NVIDIA cards in my computer room... However, my relatives do have a computer with an NVIDIA card, and they gave me permission to use it for testing, which I'll do tomorrow.

**Comment by tildearrow** [comment] 2019-04-07 04:24
OK, so I tested under NVIDIA, and seems like I could reproduce, but in my case it gets even worse:

- It works (with some stutter) for 10 seconds
- Then it suddenly disables VSync and goes full-speed (and therefore causes tearing)

I'll try to check why is this occurring within 1 to 2 days.

**Comment by tildearrow** [comment] 2019-04-10 17:54
I am profoundly sorry but I need to suspend this issue for no more than 1 month.

I do not possess any good NVIDIA cards to test with (the only one I could get my hands on is in my relatives' computer, however it is 
pretty much worthless since even glxgears displays stuttering on it), plus I have found a major issue with the NVIDIA driver: DRM_WAIT_VBLANK refuses to work.                      

Furthermore I tried modeset and actually made the issue worse as the thing is unable to open the card anymore because `Invalid argument` (seriously, this errno message is the vaguest as it doesn't tell me what argument could be invalid and I swear I hate that).    

I'm really sorry, I cannot work on it right now. I have incentives to do so, but I simply can't if I don't have the resources.

While I could just give up and disregard NVIDIA (like Drew DeVault did), I have no valid reason to do that since it does not solve anything and NVIDIA users have already settled (and I do not feel like neglecting them as I am aware of its consequences).

Once again, I cannot go any further. I am sorry but I truly can't.

I will re-open this issue as soon as I pick up a better NVIDIA card and begin testing/fixing with it.

**Comment by tildearrow** [comment] 2019-04-12 02:35
OK, so now I got an NVIDIA card and am going to try fixing this issue.

**Comment by tildearrow** [comment] 2019-04-14 06:27
I've made some changes to the waiting logic (using `glXWaitVideoSync` instead of DRM VBlank) in the [nvidia](https://github.com/tildearrow/kwin-lowlatency/tree/nvidia) branch. Please test that branch out, and tell me if it works (or at least is better).

(by the way, what is your card's model?)

**Comment by Sporif** [comment] 2019-04-14 08:48
Holy shit that is smooth, it feels much better now. And the delay is far lower than stock KWin, with the cursor only slightly ahead of the title bar when dragging windows. I can't thank you enough for this!

(The card I use is a GTX 1080)

**Comment by tildearrow** [comment] 2019-04-14 18:15
Fixes merged to main branch. Thank you for the bug report!

(release still pending however, until 5.15.5)

**Comment by Sporif** [comment] 2019-04-15 00:00
Unfortunately 5e2f59e made it stuttery again.  :confused:

**Comment by Sporif** [comment] 2019-04-15 10:39
I don't know how it works but it seems the removal of  `- options->vBlankTime()` is the cause. Keeping the other parts of that commit doesn't cause stuttering.

**Comment by tildearrow** [comment] 2019-04-15 16:03
I attempted to lower the latency (I didn't see stutter while testing this) but now that you say stuttering is back, I will take a look.

The reason why I removed vBlankTime was because it was fixed to 6ms, so I didn't understand why it was there.

**Comment by tildearrow** [comment] 2019-04-18 18:51
I have merged a few commits which add some options to the Settings > Display and Monitor > Compositor section to tweak and balance latency/stutter. Can you please test it out and tell me if it helps?

(note: you'll have to install the compositor for the section to work, so [here is a PKGBUILD](https://gist.github.com/tildearrow/86f70b3ffddab0c2fba1a06a5b86ccb0))

(if not using Arch please tell me)

(if the new options still don't appear:
  - try doing `kcmshell5 kwincompositing`
  - try doing `kcminit`
)

**Comment by Sporif** [comment] 2019-04-18 19:01
I was testing it but honestly it seems nearly perfect already. The only thing I feel can be improved is the resizing of windows, it looks like that runs at 60fps instead of the refresh rate (and resizing takes a lof of cpu usage but that might be a limitation of Xorg since it happens on other compositors as well)

**Comment by tildearrow** [comment] 2019-04-18 19:25
Seems great.

Yep, pretty much an X.Org limitation, but I will eventually take a look at it and try to improve. Thanks for the feedback!

**Closed as completed by tildearrow** 2019-04-18 19:25 UTC
Labels: done
