### ISSUE TITLE
[Feature idea] Re-implement fullscreen unredirection back

### ISSUE THREAD

**Issue by clapbr** [tildearrow/kwin-lowlatency#1] opened 2019-03-30 02:27 UTC
First of all, thanks for this, it's working really well for me, no issues yet and browsers/scrolling is smooth as butter now, I've finally come back from compton :) Oddly enough my trusty stutterless compton was the old one with --vsync=opengl, which used the same method you implemented here (dev deprecated it recently).

Now to the point, kwin used to do fullscreen unredirection so you could play games without compositor overhead and still alt+tab to a composited desktop. Mutter and compton still can do that but kwin deprecated it in favor of totally disabling it with a Block composition window rule OR by application's request (https://blog.martin-graesslin.com/blog/2016/08/opengl-changes-in-kwin-compositing/). What's your thoughts on bringing the feature back, at least as an option? Seems to align with the forks goal.

**Comment by tildearrow** [comment] 2019-04-01 19:19
OK, so I've traced the removal commit to 996ee34e14ece93421fee7bf7447ecfa785871d1.

The reason why KWin fullscreen un-redirection was removed was because it looked a lot like a hack, and didn't even work in some graphics cards.

But I'll try doing some experiments on bringing the feature back in a separate branch soon.

**Comment by clapbr** [comment] 2019-04-01 19:21
Might be worth looking into how mutter does it, I've heard it works well enough no one bothers turning compositor off in Gnome.

**Comment by clapbr** [comment] 2019-04-04 19:12
Someone on reddit shared this useful script that enables/suspend compositing based on window properties, https://gist.github.com/Sporif/8f472bc603dac7564fa12ee0a1091498 - Tried with a couple of games and seems to work.

**Comment by tildearrow** [comment] 2019-04-06 04:19
I've created a new branch named "unredirect" with the changes in place. Please test and tell me if it works. Will merge if does for most users.

(note: if building and testing in-place (e.g. `./bin/kwin_x11`), remember to copy `<buildDir>/bin/org.kde.kwin.scenes/KWinSceneOpenGL.so` to `/usr/lib/qt/plugins/org.kde.kwin.scenes/KWinSceneOpenGL.so`)

(**also: [PKGBUILD for Arch Linux with unredirect](https://gist.github.com/tildearrow/6aafab6af094536d5e434edf8a2be083)**)

**Comment by clapbr** [comment] 2019-04-06 11:37
> I've created a new branch named "unredirect" with the changes in place. Please test and tell me if it works. Will merge if does for most users.
> 
> (note: if building and testing in-place (e.g. `./bin/kwin_x11`), remember to copy `<buildDir>/bin/org.kde.kwin.scenes/KWinSceneOpenGL.so` to `/usr/lib/qt/plugins/org.kde.kwin.scenes/KWinSceneOpenGL.so`)

Couldn't make it work, tried putting UnredirectFullscreen=true under [Compositing] in kwinrc but still no luck.

**Comment by tildearrow** [comment] 2019-04-06 15:49
Did you build the right branch?
If so, is it that the compositor crashed?

(by the way, unredirection is enabled by default)

**Comment by clapbr** [comment] 2019-04-06 16:42
> Did you build the right branch?
> If so, is it that the compositor crashed?
> 
> (by the way, unredirection is enabled by default)

Figured it out, it was my tiling script messing it up. Tested unigine benchs and a couple of dxvk games and it's working now :1st_place_medal:

**Comment by tildearrow** [comment] 2019-04-07 23:42
I'm not merging this yet because I have noticed an issue that causes KWin to use 100% CPU time when unredirecting under specific conditions.

Edit: fixed in 51a6b5fe2941c17221364b07d5ebb54a9ea29bf4

**Comment by laloch** [comment] 2019-04-08 12:21
@clapbr : Could you please share which tiling script you use and what was the issue with unredirection of fullscreen clients? Thanks.

**Comment by clapbr** [comment] 2019-04-08 18:37
> @clapbr : Could you please share which tiling script you use and what was the issue with unredirection of fullscreen clients? Thanks.

It was an old version of quarter-tiling, for some reason the screen would not unredirect with it enabled. I've just migrated to a better maintained script (https://github.com/kwin-scripts/kwin-tiling) and had no problems since.

**Comment by laloch** [comment] 2019-04-09 11:21
@clapbr: Thanks for the reply. I asked, because I'm one of the maintainers of kwin-tiling, so I wanted to know whether it was problem with our script or not.

**Comment by Sporif** [comment] 2019-04-10 11:45
Unredirection seems to work well on native games, proton games and games launched directly from wine. But strangely it doesn't work for games started from a non-native launcher like battle.net or origin. For example if I start Overwatch directly it works, but from battle.net it doesn't.

Edit: Ok this just seems very inconsistent, alt-tabbing out and back in is enough to stop unredirection form working in certain games.

**Comment by tildearrow** [comment] 2019-04-15 19:03
Can you please make a list of games that don't unredirect well? I've tested with RetroArch, Xonotic and StepMania (under both AMD and NVIDIA) and seems to work in my side, even after doing alt-tab (proof is that the "Show FPS" graph disappears when unredirecting and under NVIDIA the draw mode changes from blit to flip).

(also, may you run `xwininfo` on the Overwatch fullscreen window as soon as unredirect stops working?)

**Comment by Sporif** [comment] 2019-04-15 20:20
I think the issue is latte-dock. `xwininfo` was showing `Override Redirect State: yes` even after Alt-tabbing. But the nvidia API/Gsync indicators were showing flipping and Gsync being disabled. I was out of ideas, tried closing latte-dock and what do you know, it went back to flipping and Gsync started working. So I thought since it happens after Alt-tabbing maybe it's the transparency of latte-dock that is the cause, and it looks like that's the case. Disabling the "hide background when not needed" setting in latte-dock has seemingly caused the issue to vanish.

Edit: Still occurs with cs:go, but restarting latte-dock fixes it. Very strange.

**Comment by tildearrow** [comment] 2019-04-24 05:56
OK so I'm beginning to reproduce the latte-dock issues with unredirect...

Edit: Actually not latte-dock issues, but seems like calfjackhost prevents unredirect from working...

**Comment by tildearrow** [comment] 2019-05-07 07:23
I've merged the unredirect branch now. KWin-lowlatency 5.15.5 going to be released in a few hours.

(I'm still leaving this issue open as there are some issues to fix for later versions)

**Comment by aufkrawall** [comment] 2019-05-10 16:16
@tildearrow 
Thanks for your efforts, vsync of KWin is now finally working well.

Fullscreen unredirection generally works for me with Mesa RX 580, but it stops to do so when the Battle.net client is running in Wine. This then also applies to native Linux programs like vkquake, they only get correctly unredirected when Battle.net is not running in the background (no matter if minimized or in Plasma's tray).

**Comment by aufkrawall** [comment] 2019-05-10 16:41
One more issue: Wine fullscreen application windows can't be opened again after alt + tabbing to the desktop, they stay black then.

**Comment by tildearrow** [comment] 2019-05-13 19:33
@aufkrawall Just confirmed the issue. However, it is not just restricted to Battle.net. It also reproduces with taskmgr for some reason.

**Comment by tildearrow** [comment] 2019-06-24 21:45
Apparently both calfjackhost and taskmgr create an invisible 32x32 window which serves as a simulated "tray" on GNOME, which interferes with unredirect. I'm working on a fix (although sort of a hack) to this problem.

Edit: The Battle.net client does the same as well.

**Comment by aufkrawall** [comment] 2019-06-25 09:29
@tildearrow Thanks for your continued efforts. Unfortunately, 09f889058ac3103a6f6c36a23ccc8dfb38f40e4b doesn't do the trick for me. When Battle.net launcher is started, unredirect is still turned off and Heroes of the Storm window doesn't recover after alt + tab by its windows just staying black.

Edit: The HotS window staying black is unrelated to unredirect, I suppose I should open a new ticket for it.

**Comment by tildearrow** [comment] 2019-06-25 16:31
Thanks for the feedback. Can you test again and provide the output of kwin_x11 when unredirect doesn't work? (especially the `no. this:` lines (if they don't appear try going back to 09f8890 and try again))

**Comment by tildearrow** [comment] 2019-06-25 16:34
When unredirection is enabled, every time you switch to a full-screen application that is busy it will display a black screen until the application repaints, but in your case the application isn't busy...

**Comment by aufkrawall** [comment] 2019-06-25 17:36
Good news: Unredirect seems to work fine now with Battle.net client and 5.16.2 (for whatever reason). :tada: 

Just the Wine black window issue remains, which also occurs without unredirect (but not with mainline kwin). It btw. also doesn't show sound volume OSD when pressing keyboard media buttons while being in HotS with unredirected compositing.
Dummy question: How do I get KWin to verbosity? When I start it via `kwin_x11 --replace`, there is no output when starting HotS.

**Comment by tildearrow** [comment] 2019-06-25 17:41
> It btw. also doesn't show sound volume OSD when pressing keyboard media buttons while being in HotS with unredirected compositing.

Yeah, that's a bug caused by the hacky workaround. I'll be fixing this for -2, or 5.16.3.

**Comment by tildearrow** [comment] 2019-06-25 17:43
> Dummy question: How do I get KWin to verbosity? When I start it via kwin_x11 --replace, there is no output when starting HotS.

By rolling back to commit 09f8890 and launching KWin via:
```
cd build
QT_PLUGIN_PATH="$PWD/bin" ./bin/kwin_x11 --replace
```

Then you'll be able to see the "yes", " yes via hack" and "no. this:" debug messages I added on that commit.

> Just the Wine black window issue remains, which also occurs without unredirect (but not with mainline kwin).

OK, thank you for telling me. This should be moved to a new issue.

**Comment by aufkrawall** [comment] 2019-06-25 19:43
Ehh, my mistake: I overlooked that you use `git checkout` in PKGBUILD. I've changed it to 09f889058ac3103a6f6c36a23ccc8dfb38f40e4b and of course it continued to work this time. Sorry!

Well, but now to the black screen issue.

**Comment by tildearrow** [comment] 2019-06-25 19:45
That's OK. If unredirection stops working at some point, please provide the `no. this:` output lines from KWin.

**Comment by Sporif** [comment] 2019-07-01 14:37
Unredirection seems to work very well now. I've tested it for a few days and not once has Gsync been disabled.

**Comment by aufkrawall** [comment] 2020-07-08 12:02
It indeed works very well here with Nvidia and latest software versions, I couldn't make it fail so far.

**Comment by tildearrow** [comment] 2020-08-07 01:59
Totally breaks in osu! (through Wine) for unknown reasons. It used to work but not anymore.

**Comment by 2X3** [comment] 2020-11-21 22:27
How to turn on unredirection in version 5.20? Is it activated using the variable in _kwinrc_?

**Comment by aufkrawall** [comment] 2021-03-05 22:15
@tildearrow There were some adjustments to make direct scanout work better with Wine: https://invent.kde.org/plasma/kwin/-/commit/7cc95d931b6d79e5b57361f8fcfa51aa806124a7 https://invent.kde.org/plasma/kwin/-/commit/7a937fc7af71cce6928fa5680adba30dff1bd298

Perhaps this can be similarly implemented for unredirection on Xorg to make it more reliable?

**Comment by tildearrow** [comment] 2021-11-24 18:35
Hopefully done with KWin-lowlatency 5.22+ and the new unredirection code.

**Closed as completed by tildearrow** 2021-11-24 18:35 UTC
Labels: done
